


version: '3.8'

services:
  backend:
    build: ./backend
    container_name: human_digital_twin_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  nodejs_backend:
    build: ./backend/nodejs_backend
    container_name: human_digital_twin_nodejs_backend
    ports:
      - "4000:4000"
    depends_on:
      - backend

  frontend:
    build: ./frontend
    container_name: human_digital_twin_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
      - nodejs_backend

  db:
    image: postgres:13
    container_name: human_digital_twin_db
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: human_digital_twin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  mongo:
    image: mongo:5.0
    container_name: human_digital_twin_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
